### ISSUE TITLE
Contact alarm

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_PETS#17]
As the system
When last contact was X days ago
Inform Job Developer to reconnect

**Comment by joaopapereira** [comment]
Original reporter: joaopapereira

**Comment by patmbolger** [comment]
Note that in this story the "contact" refers to activity by the Job Seeker - activity could be submitting a job application, checking in with the Job Developer, updating his profile, and other actions.  (this qualification is necessary because there is also an "inactivity alert" generated by the system when an Employer is taking too long to respond to a job submission (by a Job Seeker or by a Job Developer on behalf of Job Seeker. - that story is described elsewhere)

**Comment by joaopapereira** [comment]
This issue was moved to AgileVentures/MetPlus_tracker#20
